### ISSUE TITLE
PyModelTime Roadmap

### ISSUE THREAD

**Issue by mdancho84** [business-science/pymodeltime#1]
# Phase 1: Prepare for a Version 0.1.0 Release

- [ ] Poetry
- [ ] GitHub Actions
- [ ] Review Modeltime Code and Workflow
- [ ] Review Algorithms 
- [ ] Investigate new algorithms `statsforecast` and `mlforecast`
- [ ] Unit Tests
- [ ] Documentation with Quarto
